##############################################
### MAKEFILE FOR VLSV PARALLEL FILE FORMAT ###
###                                        ###
###       DO NOT EDIT THIS FILE !!!        ###
##############################################

# Define default architecture and include the 
# corresponding Makefile:
ARCH ?= arto
include Makefile.${ARCH}

# Distribution package name (do not edit)
DIR=vlsv
DIST=vlsv_v01_001.tar

# Build targets

default: lib conv_mtx_vlsv

clean:
	rm -rf *~ *.o *.a *.tar *.tar.gz vlsv2silo conv_mtx_vlsv

dist:
	ln -s ${CURDIR} ${DIR}
	tar -rf ${DIST} ${DIR}/COPYING* ${DIR}/Makefile
	tar -rf ${DIST} ${DIR}/*.h ${DIR}/*.cpp ${DIR}/*.pdf
	gzip -9 ${DIST}
	rm ${DIR}

# Dependencies

DEPS_AMR = vlsv_amr.h vlsv_amr.cpp
DEPS_COMMON = muxml.h vlsv_common.h
DEPS_FILE_IO = portable_file_io.h portable_file_io.cpp
DEPS_MULTI_IO=multi_io_unit.h multi_io_unit.cpp
DEPS_MUXML = muxml.h muxml.cpp
DEPS_VLSVCOMMON = vlsv_common.h vlsv_common.cpp
DEPS_VLSVCOMMON_MPI = ${DEPS_VLSVCOMMON} vlsv_common_mpi.h vlsv_common_mpi.cpp
DEPS_READER = ${DEPS_VLSVCOMMON} vlsv_reader.h vlsv_reader.cpp
DEPS_PARAREADER = ${DEPS_READER} vlsv_reader_parallel.h vlsv_reader_parallel.cpp
DEPS_WRITER = ${DEPS_VLSVCOMMON} vlsv_writer.h vlsv_writer.cpp
DEPS_VLSV2SILO = vlsv_reader.o muxml.o vlsv_common.o vlsv2silo.cpp

OBJS=multi_io_unit.o muxml.o vlsv_amr.o vlsv_common.o vlsv_common_mpi.o vlsv_reader.o vlsv_reader_parallel.o vlsv_writer.o portable_file_io.o

# Build rules

lib: ${OBJS}
	${AR} r libvlsv.a ${OBJS}

portable_file_io.o: ${DEPS_FILE_IO}
	${CMP} ${CXXFLAGS} -fPIC ${FLAGS} -c portable_file_io.cpp

multi_io_unit.o: ${DEPS_MULTI_IO}
	${CMP} ${CXXFLAGS} -fPIC ${FLAGS} -c multi_io_unit.cpp

muxml.o: ${DEPS_MUXML}
	${CMP} ${CXXFLAGS} -fPIC ${FLAGS} -c muxml.cpp

vlsv_amr.o: ${DEPS_AMR}
	${CMP} ${CXXFLAGS} -ffast-math -fPIC ${FLAGS} -c vlsv_amr.cpp

vlsv_common.o: ${DEPS_VLSVCOMMON}
	${CMP} ${CXXFLAGS} -fPIC ${FLAGS} -c vlsv_common.cpp

vlsv_common_mpi.o: ${DEPS_VLSVCOMMON_MPI}
	${CMP} ${CXXFLAGS} -fPIC ${FLAGS} -c vlsv_common_mpi.cpp

vlsv_reader.o: ${DEPS_READER}
	${CMP} ${CXXFLAGS} -fPIC ${FLAGS} -o vlsv_reader.o -c vlsv_reader.cpp

vlsv_reader_parallel.o: ${DEPS_PARAREADER}
	${CMP} ${CXXFLAGS} -fPIC ${FLAGS} -o vlsv_reader_parallel.o -c vlsv_reader_parallel.cpp

vlsv_writer.o: ${DEPS_WRITER}
	${CMP} ${CXXFLAGS} -fPIC ${FLAGS} -o vlsv_writer.o -c vlsv_writer.cpp

vlsv2silo: ${DEPS_VLSV2SILO}
	${CMP} ${CXXFLAGS} ${FLAGS} -o vlsv2silo vlsv2silo.cpp ${INC_SILO} -L${CURDIR} -lvlsv ${LIB_SILO}

conv_mtx_vlsv: conv_mtx_vlsv.cpp $(lib)
	${CMP} ${CXXFLAGS} ${FLAGS} -o conv_mtx_vlsv conv_mtx_vlsv.cpp -L${CURDIR} -lvlsv
