##############################################
### MAKEFILE FOR VLSV PARALLEL FILE FORMAT ###
###                                        ###
###       DO NOT EDIT THIS FILE !!!        ###
##############################################

# Define default architecture and include the 
# corresponding Makefile:
ARCH ?= arto
include Makefile.${ARCH}

# Distribution package name (do not edit)
DIR=vlsv
DIST=vlsv_v01_001.tar

# Build targets

default: lib vlsv2silo

clean:
	rm -rf *~ *.o *.a *.tar *.tar.gz vlsv2silo

dist:
	ln -s ${CURDIR} ${DIR}
	tar -rf ${DIST} ${DIR}/COPYING* ${DIR}/Makefile
	tar -rf ${DIST} ${DIR}/*.h ${DIR}/*.cpp ${DIR}/*.pdf
	gzip -9 ${DIST}
	rm ${DIR}

# Dependencies

DEPS_COMMON = muxml.h vlsv_common.h
DEPS_MULTI_IO=multi_io_unit.h multi_io_unit.cpp
DEPS_MUXML = muxml.h muxml.cpp
DEPS_VLSVCOMMON = vlsv_common.h vlsv_common.cpp
DEPS_READER = ${DEPS_VLSCOMMON} vlsvreader.h vlsvreader2.cpp
DEPS_WRITER = ${DEPS_VLSCOMMON} vlsvwriter.h vlsvwriter2.cpp
DEPS_VLSV2SILO = vlsvreader.o muxml.o vlsv_common.o vlsv2silo.cpp

OBJS=multi_io_unit.o muxml.o vlsv_common.o vlsvreader.o vlsvwriter.o

# Build rules

lib: ${OBJS}
	${AR} r libvlsv.a ${OBJS}

multi_io_unit.o: ${DEPS_MULTI_IO}
	${CMP} ${CXXFLAGS} ${FLAGS} -c multi_io_unit.cpp

muxml.o: ${DEPS_MUXML}
	${CMP} ${CXXFLAGS} ${FLAGS} -c muxml.cpp

vlsv_common.o: ${DEPS_VLSVCOMMON}
	${CMP} ${CXXFLAGS} ${FLAGS} -c vlsv_common.cpp

vlsvreader.o: ${DEPS_READER}
	${CMP} ${CXXFLAGS} ${FLAGS} -o vlsvreader.o -c vlsvreader2.cpp

vlsvwriter.o: ${DEPS_WRITER}
	${CMP} ${CXXFLAGS} ${FLAGS} -o vlsvwriter.o -c vlsvwriter2.cpp

vlsv2silo: ${DEPS_VLSV2SILO}
	${CMP} ${CXXFLAGS} ${FLAGS} -o vlsv2silo vlsv2silo.cpp ${INC_SILO} -L${CURDIR} -lvlsv ${LIB_SILO}
